language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then mkdir -p build/logs && vendor/bin/phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then phpunit ; fi


after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/coveralls --coverage_clover=build/logs/clover.xml -v ; fi
